# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
development:
  secret_key_base: ENV["FACEBOOK_KEY"]
  secret_token: ENV["FACEBOOK_SECRET"]

test:
  secret_key_base: ENV["FACEBOOK_KEY"]
  secret_token: ENV["FACEBOOK_SECRET"]
#  secret_key_base: 4da652febe6fba51eb1c120e6c88144ba4779effbd74ac91d65e00abadd8a829d8b637fe4949262fd26f744a3e16a191bb750725eb918cab9b6b3a8bed0b9366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
